/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.Conexao;
import dao.UsuarioDAO;
import java.sql.Connection;
import javax.swing.JOptionPane;
import model.Usuario;
import view.MedicoView;
import view.MenuPrincipal;
import view.PacienteView;


/**
 *
 * @author Ferraz Caianda
 */
public class LogoView extends javax.swing.JFrame {

    /**
     * Creates new form LogoView
     */
    public LogoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nomeusuario = new javax.swing.JTextField();
        Senha = new javax.swing.JPasswordField();
        btEntrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BEM-VINDO");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(100, 130, 235, 43);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SENHA");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 340, 120, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Digite suas credenciais de acesso ao sistema");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(80, 180, 270, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("USUÁRIO");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(90, 257, 70, 20);

        Nomeusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeusuarioActionPerformed(evt);
            }
        });
        jPanel2.add(Nomeusuario);
        Nomeusuario.setBounds(90, 290, 320, 30);
        jPanel2.add(Senha);
        Senha.setBounds(90, 370, 320, 30);

        btEntrar.setBackground(new java.awt.Color(0, 0, 0));
        btEntrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btEntrar.setText("ENTRAR");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });
        jPanel2.add(btEntrar);
        btEntrar.setBounds(170, 430, 110, 28);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(360, 0, 440, 550);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clinica_300x300.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel3.add(jLabel1);
        jLabel1.setBounds(27, 55, 310, 350);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 360, 550);

        setSize(new java.awt.Dimension(816, 559));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NomeusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeusuarioActionPerformed

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed

       try{
        Connection con = Conexao.getConnection();

        UsuarioDAO dao = new UsuarioDAO(con);

        Usuario u = dao.LoginView(
                Nomeusuario.getText(),
                Senha.getText()
        );
        if (u != null) {

            JOptionPane.showMessageDialog(this, "Login OK");
            SessaoUsuario.iniciar(u);

            String perfil = u.getNivelAcesso();

            if ("ADMINISTRADOR".equals(perfil)) {
                new MenuPrincipal().setVisible(true);

            } else if ("RECEPCIONISTA".equals(perfil)) {
                new PacienteView().setVisible(true);

            } else if ("MEDICO".equals(perfil)) {
                new MedicoView().setVisible(true);
            }
            this.dispose();
        } else {
                JOptionPane.showMessageDialog(this,
                    "Utilizador ou senha inválidos");
        }
            } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Erro: " + e.getMessage());
    }
    }//GEN-LAST:event_btEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nomeusuario;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JButton btEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
