/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Ferraz Caianda
 */
public class MedicoView extends javax.swing.JFrame {

    /**
     * Creates new form MedicoView
     */
    public MedicoView() {
        initComponents();
        InterfaceUsuario.aplicarUsuarioLogado(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pesqMedic = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btLimpar = new javax.swing.JButton();
        btConsulta = new javax.swing.JButton();
        btLimpar1 = new javax.swing.JButton();
        PANEL = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2Geral = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CADASTRAR MEDICO");
        setResizable(false);
        getContentPane().setLayout(null);

        pesqMedic.setBackground(new java.awt.Color(0, 0, 51));
        pesqMedic.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MÉDICO");
        pesqMedic.add(jLabel2);
        jLabel2.setBounds(260, 70, 340, 40);

        jPanel1.setLayout(null);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel6.setLayout(null);

        btLimpar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btLimpar.setText("Fechar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        jPanel6.add(btLimpar);
        btLimpar.setBounds(30, 390, 75, 22);

        btConsulta.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btConsulta.setText("Consultar");
        btConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaActionPerformed(evt);
            }
        });
        jPanel6.add(btConsulta);
        btConsulta.setBounds(20, 30, 79, 22);

        btLimpar1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btLimpar1.setText("LIMPAR");
        btLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpar1ActionPerformed(evt);
            }
        });
        jPanel6.add(btLimpar1);
        btLimpar1.setBounds(20, 90, 75, 22);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(10, 10, 120, 440);

        PANEL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        PANEL.setLayout(null);

        jTable2Geral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Idade", "Sexo", "Histórico Médico", "Data", "Hora", "Estado da Consulta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2Geral.setColumnSelectionAllowed(true);
        jTable2Geral.setDragEnabled(true);
        jTable2Geral.setSelectionBackground(new java.awt.Color(0, 102, 51));
        jScrollPane2.setViewportView(jTable2Geral);

        PANEL.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 800, 410);

        jPanel1.add(PANEL);
        PANEL.setBounds(150, 10, 820, 440);

        pesqMedic.add(jPanel1);
        jPanel1.setBounds(10, 120, 980, 480);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText(" NEW HORIZONTE");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 220, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("BEM-VINDO AO SISTEMA DE GESTÃO");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 30, 240, 30);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(720, 20, 240, 22);

        btPesquisar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btPesquisar.setText("PESQUISAR");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        jPanel2.add(btPesquisar);
        btPesquisar.setBounds(620, 20, 98, 22);

        pesqMedic.add(jPanel2);
        jPanel2.setBounds(20, 10, 970, 60);

        getContentPane().add(pesqMedic);
        pesqMedic.setBounds(0, 0, 1000, 650);

        setSize(new java.awt.Dimension(1016, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLimparActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLimpar1ActionPerformed

    private void btConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaActionPerformed
        // TODO add your handling code here:
        new ConsultaView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PANEL;
    private javax.swing.JButton btConsulta;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btLimpar1;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2Geral;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pesqMedic;
    // End of variables declaration//GEN-END:variables
}
