/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.Conexao;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author Ferraz Caianda
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        InterfaceUsuario.aplicarUsuarioLogado(this);
        configurarDashboard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldpesquisar = new javax.swing.JTextField();
        btPaciente = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btFuncionario = new javax.swing.JButton();
        btMedicoNovo = new javax.swing.JButton();
        btRelatorio = new javax.swing.JButton();
        btProntuario = new javax.swing.JButton();
        btpaciente = new javax.swing.JButton();
        btConsulte1 = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        Fechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText(" NEW HORIZONTE");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 220, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("BEM-VINDO AO SISTEMA DE GESTÃO");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 30, 240, 30);
        jPanel2.add(jTextFieldpesquisar);
        jTextFieldpesquisar.setBounds(750, 20, 220, 22);

        btPaciente.setBackground(new java.awt.Color(204, 204, 255));
        btPaciente.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btPaciente.setText("Pesquisar");
        btPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPacienteActionPerformed(evt);
            }
        });
        jPanel2.add(btPaciente);
        btPaciente.setBounds(650, 20, 90, 22);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(10, 10, 980, 60);

        jPanel5.setBackground(new java.awt.Color(0, 0, 51));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel5.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 255));
        jLabel8.setText("PAINEL DO ADMINISTRADOR");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(230, 20, 540, 40);

        jPanel6.setBackground(new java.awt.Color(0, 0, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(null);

        btFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btFuncionario.setText("Outros Funcionários");
        btFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFuncionarioActionPerformed(evt);
            }
        });
        jPanel6.add(btFuncionario);
        btFuncionario.setBounds(10, 220, 140, 30);

        btMedicoNovo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btMedicoNovo.setText("Gerir Médicos");
        btMedicoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMedicoNovoActionPerformed(evt);
            }
        });
        jPanel6.add(btMedicoNovo);
        btMedicoNovo.setBounds(10, 20, 140, 30);

        btRelatorio.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btRelatorio.setText("Relatórios");
        btRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioActionPerformed(evt);
            }
        });
        jPanel6.add(btRelatorio);
        btRelatorio.setBounds(10, 280, 140, 30);

        btProntuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btProntuario.setText("Prontuários");
        btProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProntuarioActionPerformed(evt);
            }
        });
        jPanel6.add(btProntuario);
        btProntuario.setBounds(10, 170, 140, 30);

        btpaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btpaciente.setText("Pacientes");
        btpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpacienteActionPerformed(evt);
            }
        });
        jPanel6.add(btpaciente);
        btpaciente.setBounds(10, 70, 140, 30);

        btConsulte1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btConsulte1.setText("Consultas");
        btConsulte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsulte1ActionPerformed(evt);
            }
        });
        jPanel6.add(btConsulte1);
        btConsulte1.setBounds(10, 120, 140, 28);

        btVoltar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btVoltar.setText("Voltar");
        jPanel6.add(btVoltar);
        btVoltar.setBounds(20, 390, 80, 20);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(10, 70, 160, 430);

        Fechar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Fechar.setText("Fechar");
        jPanel5.add(Fechar);
        Fechar.setBounds(880, 480, 80, 20);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(10, 80, 980, 520);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 1000, 640);

        setSize(new java.awt.Dimension(1016, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void configurarDashboard() {
        prepararMenuLateral();
        adicionarResumoDashboard();

        btVoltar.setText("Sair");
        btVoltar.addActionListener(evt -> sairDoSistema());
        Fechar.addActionListener(evt -> System.exit(0));
    }

    private void prepararMenuLateral() {
        InterfaceUsuario.prepararBotaoMenu(btMedicoNovo);
        InterfaceUsuario.prepararBotaoMenu(btpaciente);
        InterfaceUsuario.prepararBotaoMenu(btConsulte1);
        InterfaceUsuario.prepararBotaoMenu(btProntuario);
        InterfaceUsuario.prepararBotaoMenu(btFuncionario);
        InterfaceUsuario.prepararBotaoMenu(btRelatorio);
        InterfaceUsuario.prepararBotaoMenu(btVoltar);
        InterfaceUsuario.prepararBotaoMenu(Fechar);
        InterfaceUsuario.prepararBotaoMenu(btPaciente);
    }

    private void adicionarResumoDashboard() {
        jPanel5.setBackground(new Color(246, 248, 252));
        jLabel8.setText("Dashboard administrativo");
        jLabel8.setFont(new Font("Segoe UI", Font.BOLD, 28));
        jLabel8.setForeground(new Color(0, 0, 51));
        jLabel8.setBounds(210, 18, 420, 36);

        JLabel boasVindas = new JLabel(
                "Bem-vindo, " + SessaoUsuario.getNomeUsuario() + " | Perfil: " + SessaoUsuario.getPerfilUsuario()
        );
        boasVindas.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        boasVindas.setForeground(new Color(80, 88, 105));
        jPanel5.add(boasVindas);
        boasVindas.setBounds(210, 55, 500, 24);

        JPanel pacientes = InterfaceUsuario.criarCardDashboard("Pacientes ativos", contar("SELECT COUNT(*) FROM paciente WHERE ativo = TRUE"), new Color(0, 153, 204));
        JPanel medicos = InterfaceUsuario.criarCardDashboard("Medicos", contar("SELECT COUNT(*) FROM medico"), new Color(0, 153, 102));
        JPanel consultas = InterfaceUsuario.criarCardDashboard("Consultas hoje", contar("SELECT COUNT(*) FROM consulta WHERE data_consulta = CURDATE()"), new Color(255, 153, 0));
        JPanel usuarios = InterfaceUsuario.criarCardDashboard("Utilizadores", contar("SELECT COUNT(*) FROM usuario"), new Color(102, 102, 204));

        jPanel5.add(pacientes);
        pacientes.setBounds(210, 105, 170, 92);
        jPanel5.add(medicos);
        medicos.setBounds(400, 105, 170, 92);
        jPanel5.add(consultas);
        consultas.setBounds(590, 105, 170, 92);
        jPanel5.add(usuarios);
        usuarios.setBounds(780, 105, 170, 92);

        JLabel atalhos = new JLabel("Acoes rapidas");
        atalhos.setFont(new Font("Segoe UI", Font.BOLD, 18));
        atalhos.setForeground(new Color(0, 0, 51));
        jPanel5.add(atalhos);
        atalhos.setBounds(210, 235, 200, 26);

        adicionarBotaoAtalho("Novo paciente", 210, 280, evt -> abrirPaciente());
        adicionarBotaoAtalho("Nova consulta", 400, 280, evt -> abrirConsulta());
        adicionarBotaoAtalho("Novo medico", 590, 280, evt -> abrirMedico());
        adicionarBotaoAtalho("Relatorios", 780, 280, evt -> abrirRelatorio());

        JLabel aviso = new JLabel("Use o menu lateral para gerir cadastros, prontuarios e relatorios.");
        aviso.setHorizontalAlignment(SwingConstants.CENTER);
        aviso.setOpaque(true);
        aviso.setBackground(new Color(255, 255, 255));
        aviso.setForeground(new Color(80, 88, 105));
        aviso.setBorder(BorderFactory.createLineBorder(new Color(225, 228, 235)));
        jPanel5.add(aviso);
        aviso.setBounds(210, 370, 740, 58);
    }

    private void adicionarBotaoAtalho(String texto, int x, int y, java.awt.event.ActionListener action) {
        JButton botao = new JButton(texto);
        botao.setFont(new Font("Segoe UI", Font.BOLD, 14));
        botao.setBackground(new Color(0, 0, 51));
        botao.setForeground(Color.WHITE);
        botao.setFocusPainted(false);
        botao.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        botao.addActionListener(action);
        botao.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botao.setBackground(new Color(26, 76, 140));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botao.setBackground(new Color(0, 0, 51));
            }
        });
        jPanel5.add(botao);
        botao.setBounds(x, y, 170, 46);
    }

    private String contar(String sql) {
        try (Connection con = Conexao.getConnection();
                PreparedStatement stmt = con.prepareStatement(sql);
                ResultSet rs = stmt.executeQuery()) {
            if (rs.next()) {
                return String.valueOf(rs.getInt(1));
            }
        } catch (Exception e) {
            return "-";
        }
        return "0";
    }

    private void abrirPaciente() {
        new PacienteView().setVisible(true);
        this.dispose();
    }

    private void abrirConsulta() {
        new ConsultaView().setVisible(true);
        this.dispose();
    }

    private void abrirMedico() {
        new NovoMedicoView().setVisible(true);
        this.dispose();
    }

    private void abrirRelatorio() {
        new RelatorioView().setVisible(true);
        this.dispose();
    }

    private void sairDoSistema() {
        int opcao = JOptionPane.showConfirmDialog(this,
                "Deseja terminar a sessao?",
                "Sair",
                JOptionPane.YES_NO_OPTION);
        if (opcao == JOptionPane.YES_OPTION) {
            SessaoUsuario.encerrar();
            new LogoView().setVisible(true);
            this.dispose();
        }
    }

    private void btFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFuncionarioActionPerformed
        // TODO add your handling code here:
        new OutrosFuncio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btFuncionarioActionPerformed

    private void btpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpacienteActionPerformed
        // TODO add your handling code here:
        abrirPaciente();
    }//GEN-LAST:event_btpacienteActionPerformed

    private void btRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatorioActionPerformed
        // TODO add your handling code here:
        abrirRelatorio();
    }//GEN-LAST:event_btRelatorioActionPerformed

    private void btPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPacienteActionPerformed
        // TODO add your handling code here:
        abrirPaciente();
    }//GEN-LAST:event_btPacienteActionPerformed

    private void btMedicoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMedicoNovoActionPerformed
        // TODO add your handling code here:
        abrirMedico();
    }//GEN-LAST:event_btMedicoNovoActionPerformed

    private void btConsulte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsulte1ActionPerformed
        // TODO add your handling code here:
        abrirConsulta();
    }//GEN-LAST:event_btConsulte1ActionPerformed

    private void btProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProntuarioActionPerformed
        // TODO add your handling code here:
        new ProntuarioView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btProntuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fechar;
    private javax.swing.JButton btConsulte1;
    private javax.swing.JButton btFuncionario;
    private javax.swing.JButton btMedicoNovo;
    private javax.swing.JButton btPaciente;
    private javax.swing.JButton btProntuario;
    private javax.swing.JButton btRelatorio;
    private javax.swing.JButton btVoltar;
    private javax.swing.JButton btpaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextFieldpesquisar;
    // End of variables declaration//GEN-END:variables
}
