/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Connection;
import dao.Conexao;
import model.Medico;
import dao.MedicoDAO;
import javax.swing.JOptionPane;


/**
 *
 * @author Ferraz Caianda
 */
public class NovoMedicoView extends javax.swing.JFrame {

    /**
     * Creates new form NovoMedicoView
     */
    public NovoMedicoView() {
        initComponents();
        InterfaceUsuario.aplicarUsuarioLogado(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ncr = new javax.swing.JTextField();
        Nomemedico = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        especialidade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btMenu = new javax.swing.JButton();
        jTextTelefone1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Novo Médico");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText(" NEW HORIZONTE");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 220, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 255));
        jLabel3.setText("BEM-VINDO AO SISTEMA DE GESTÃO");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 30, 240, 30);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(20, 10, 970, 70);

        jPanel5.setBackground(new java.awt.Color(0, 0, 51));
        jPanel5.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PAINEL DO ADMINISTRADOR");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(290, 10, 370, 30);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOVO MÉDICO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel7.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("NOME COMPLETO:");
        jPanel7.add(jLabel7);
        jLabel7.setBounds(150, 40, 120, 15);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("N C R:");
        jPanel7.add(jLabel10);
        jLabel10.setBounds(150, 320, 150, 15);
        jPanel7.add(ncr);
        ncr.setBounds(150, 340, 450, 30);

        Nomemedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomemedicoActionPerformed(evt);
            }
        });
        jPanel7.add(Nomemedico);
        Nomemedico.setBounds(150, 60, 450, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("TELEFONE:");
        jPanel7.add(jLabel9);
        jLabel9.setBounds(150, 110, 70, 15);
        jPanel7.add(email);
        email.setBounds(150, 210, 450, 30);
        jPanel7.add(especialidade);
        especialidade.setBounds(150, 270, 450, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("ENDEREÇO DE EMAIL:");
        jPanel7.add(jLabel13);
        jLabel13.setBounds(150, 190, 150, 15);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("ESPECIALIDADE:");
        jPanel7.add(jLabel14);
        jLabel14.setBounds(150, 250, 150, 20);

        btSalvar.setBackground(new java.awt.Color(0, 204, 51));
        btSalvar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel7.add(btSalvar);
        btSalvar.setBounds(830, 360, 80, 28);

        btMenu.setBackground(new java.awt.Color(153, 153, 153));
        btMenu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btMenu.setText("Menu");
        btMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuActionPerformed(evt);
            }
        });
        jPanel7.add(btMenu);
        btMenu.setBounds(830, 320, 80, 28);
        jPanel7.add(jTextTelefone1);
        jTextTelefone1.setBounds(150, 140, 450, 30);

        jPanel5.add(jPanel7);
        jPanel7.setBounds(10, 50, 950, 450);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(20, 90, 970, 540);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 1000, 650);

        setSize(new java.awt.Dimension(1016, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
    try{
        Medico m = new Medico();
    m.setNome(Nomemedico.getText());
    m.setCrm(ncr.getText());
    m.setEspecialidade(especialidade.getText());
    m.setTelefone(jTextTelefone1.getText());
    m.setEmail(email.getText());
    Connection con = Conexao.getConnection();
    MedicoDAO dao = new MedicoDAO(con);
    dao.salvar(m);
    JOptionPane.showMessageDialog(this, "Médico Cadastrado com sucesso!");
    } catch (Exception e){
        JOptionPane.showMessageDialog(this, "Erro!" + e.getMessage());
    }

    
   

    
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuActionPerformed
        // TODO add your handling code here:
        new MenuPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btMenuActionPerformed

    private void NomemedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomemedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomemedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoMedicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoMedicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoMedicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoMedicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoMedicoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nomemedico;
    private javax.swing.JButton btMenu;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextField email;
    private javax.swing.JTextField especialidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextTelefone1;
    private javax.swing.JTextField ncr;
    // End of variables declaration//GEN-END:variables
}
