/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.Conexao;
import javax.swing.JOptionPane;
import model.Usuario;
import dao.UsuarioDAO;
import java.sql.Connection;


/**
 *
 * @author Ferraz Caianda
 */
public class OutrosFuncio extends javax.swing.JFrame {

    /**
     * Creates new form OutrosFuncio
     */
    public OutrosFuncio() {
        initComponents();
        InterfaceUsuario.aplicarUsuarioLogado(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        PerfilAcesso = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        NomeFunc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        btSalvar1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        senha = new javax.swing.JPasswordField();
        btvoltar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        NomeAcesso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Outros Funcionários");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 204, 255));
        jPanel4.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText(" NEW HORIZONTE");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 220, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("SISTEMA DE GESTÃO");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 30, 240, 30);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(10, 10, 980, 80);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PAINEL DO ADMINISTRADOR");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(10, 10, 380, 30);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Novo Funcionário", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel7.setLayout(null);

        PerfilAcesso.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PerfilAcesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recepção", "Administrador", "Médico" }));
        jPanel7.add(PerfilAcesso);
        PerfilAcesso.setBounds(200, 330, 460, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Nome Completo");
        jPanel7.add(jLabel7);
        jLabel7.setBounds(200, 50, 120, 17);

        NomeFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeFuncActionPerformed(evt);
            }
        });
        jPanel7.add(NomeFunc);
        NomeFunc.setBounds(200, 80, 450, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Perfil de Acesso");
        jPanel7.add(jLabel12);
        jLabel12.setBounds(200, 300, 160, 20);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Senha");
        jPanel7.add(jLabel9);
        jLabel9.setBounds(200, 210, 110, 20);

        btVoltar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btVoltar.setText("VOLTAR");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        jPanel7.add(btVoltar);
        btVoltar.setBounds(590, 430, 77, 22);

        btSalvar1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btSalvar1.setText("SALVAR");
        jPanel7.add(btSalvar1);
        btSalvar1.setBounds(690, 430, 77, 22);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel7.add(jLabel14);
        jLabel14.setBounds(70, 240, 150, 20);

        btSalvar.setBackground(new java.awt.Color(0, 204, 51));
        btSalvar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel7.add(btSalvar);
        btSalvar.setBounds(810, 380, 70, 30);
        jPanel7.add(senha);
        senha.setBounds(200, 250, 450, 30);

        btvoltar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btvoltar.setForeground(new java.awt.Color(204, 204, 255));
        btvoltar.setText("Menu");
        btvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvoltarActionPerformed(evt);
            }
        });
        jPanel7.add(btvoltar);
        btvoltar.setBounds(810, 350, 70, 20);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Nome de Usuário");
        jPanel7.add(jLabel10);
        jLabel10.setBounds(200, 130, 120, 17);

        NomeAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeAcessoActionPerformed(evt);
            }
        });
        jPanel7.add(NomeAcesso);
        NomeAcesso.setBounds(200, 160, 450, 30);

        jPanel5.add(jPanel7);
        jPanel7.setBounds(30, 50, 900, 430);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(10, 100, 950, 520);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(30, 0, 1010, 650);

        setSize(new java.awt.Dimension(1019, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        try {
        if (NomeFunc.getText().trim().isEmpty()
                || NomeAcesso.getText().trim().isEmpty()
                || senha.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this,
                    "Preencha nome completo, nome de usuario e senha.");
            return;
        }

        Usuario u = new Usuario();

        u.setNome(NomeFunc.getText().trim());
        u.setUsername(NomeAcesso.getText().trim());
        u.setSenha(new String(senha.getPassword()));
        u.setNivelAcesso(PerfilAcesso.getSelectedItem().toString());

        Connection con = Conexao.getConnection();

        UsuarioDAO dao = new UsuarioDAO(con);
        dao.salvar(u);

        JOptionPane.showMessageDialog(this,
                "Utilizador cadastrado com sucesso!");
        NomeFunc.setText("");
        NomeAcesso.setText("");
        senha.setText("");

    }catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Erro ao cadastrar utilizador:\n" + e.getMessage());
    }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void NomeFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeFuncActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        // TODO add your handling code here:
        new MedicoView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvoltarActionPerformed
        // TODO add your handling code here:
        new MenuPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btvoltarActionPerformed

    private void NomeAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeAcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeAcessoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutrosFuncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutrosFuncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutrosFuncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutrosFuncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutrosFuncio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NomeAcesso;
    private javax.swing.JTextField NomeFunc;
    private javax.swing.JComboBox<String> PerfilAcesso;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSalvar1;
    private javax.swing.JButton btVoltar;
    private javax.swing.JButton btvoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField senha;
    // End of variables declaration//GEN-END:variables
}
