/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.PacienteDao;
import java.sql.Date;
import javax.swing.JOptionPane;
import model.Paciente;


/**
 *
 * @author Ferraz Caianda
 */
public class PacienteView extends javax.swing.JFrame {
        /**
     * Creates new form PacienteView
     */
    public PacienteView() {
        initComponents();
        InterfaceUsuario.aplicarUsuarioLogado(this);
        idPaciente.setEditable(false);
        DADOSPACIENTE.revalidate();
        DADOSPACIENTE.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        DADOSPACIENTE = new javax.swing.JPanel();
        sexo = new javax.swing.JComboBox<>();
        idPaciente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDataNascimento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtHistorico = new javax.swing.JTextField();
        endereco = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btMenu1 = new javax.swing.JButton();
        btMenu2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btAgendar = new javax.swing.JButton();
        btNovoCadastro = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btMenu = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2Geral = new javax.swing.JTable();
        btPesquisar = new javax.swing.JButton();
        pesquisaPaciente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paciente");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(51, 204, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 650));
        jPanel4.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText(" NEW HORIZONTE");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 10, 220, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("       SISTEMA DE GESTÃO");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 30, 200, 30);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(10, 10, 980, 60);

        jPanel1.setLayout(null);

        DADOSPACIENTE.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CADASTRAR PACIENTE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        DADOSPACIENTE.setLayout(null);

        sexo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoActionPerformed(evt);
            }
        });
        DADOSPACIENTE.add(sexo);
        sexo.setBounds(150, 90, 72, 21);

        idPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPacienteActionPerformed(evt);
            }
        });
        DADOSPACIENTE.add(idPaciente);
        idPaciente.setBounds(140, 20, 60, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Nome Completo:");
        DADOSPACIENTE.add(jLabel7);
        jLabel7.setBounds(10, 50, 120, 20);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        DADOSPACIENTE.add(txtNome);
        txtNome.setBounds(140, 50, 280, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Sexo:");
        DADOSPACIENTE.add(jLabel12);
        jLabel12.setBounds(70, 90, 50, 20);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Data de Nascimento:");
        DADOSPACIENTE.add(jLabel10);
        jLabel10.setBounds(10, 120, 140, 30);

        txtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascimentoActionPerformed(evt);
            }
        });
        DADOSPACIENTE.add(txtDataNascimento);
        txtDataNascimento.setBounds(150, 120, 280, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Histórico Médico:");
        DADOSPACIENTE.add(jLabel11);
        jLabel11.setBounds(520, 80, 110, 17);

        txtHistorico.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        DADOSPACIENTE.add(txtHistorico);
        txtHistorico.setBounds(650, 80, 280, 100);

        endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoActionPerformed(evt);
            }
        });
        DADOSPACIENTE.add(endereco);
        endereco.setBounds(660, 50, 270, 22);
        DADOSPACIENTE.add(txtTelefone);
        txtTelefone.setBounds(660, 20, 270, 22);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Telefone:");
        DADOSPACIENTE.add(jLabel8);
        jLabel8.setBounds(570, 20, 70, 17);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Endereço:");
        DADOSPACIENTE.add(jLabel9);
        jLabel9.setBounds(570, 50, 80, 17);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Código Paciente:");
        DADOSPACIENTE.add(jLabel13);
        jLabel13.setBounds(20, 20, 110, 17);

        btMenu1.setBackground(new java.awt.Color(153, 153, 153));
        btMenu1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btMenu1.setText("Menu");
        btMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenu1ActionPerformed(evt);
            }
        });
        DADOSPACIENTE.add(btMenu1);
        btMenu1.setBounds(830, 320, 80, 28);

        btMenu2.setBackground(new java.awt.Color(153, 153, 153));
        btMenu2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btMenu2.setText("Menu");
        btMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenu2ActionPerformed(evt);
            }
        });
        DADOSPACIENTE.add(btMenu2);
        btMenu2.setBounds(830, 320, 80, 28);

        jPanel1.add(DADOSPACIENTE);
        DADOSPACIENTE.setBounds(10, 10, 960, 190);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AÇÕES", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel6.setLayout(null);

        btAgendar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btAgendar.setText("AGENDAR");
        btAgendar.setActionCommand("Agendar");
        btAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgendarActionPerformed(evt);
            }
        });
        jPanel6.add(btAgendar);
        btAgendar.setBounds(830, 10, 100, 22);

        btNovoCadastro.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btNovoCadastro.setText("NOVO");
        btNovoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoCadastroActionPerformed(evt);
            }
        });
        jPanel6.add(btNovoCadastro);
        btNovoCadastro.setBounds(60, 10, 72, 22);

        btSalvar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btSalvar.setText("SALVAR");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel6.add(btSalvar);
        btSalvar.setBounds(140, 10, 77, 22);

        btEditar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btEditar.setText("EDITAR");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        jPanel6.add(btEditar);
        btEditar.setBounds(230, 10, 74, 22);

        btExcluir.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btExcluir.setText("EXCLUIR");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel6.add(btExcluir);
        btExcluir.setBounds(310, 10, 81, 22);

        btLimpar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btLimpar.setText("LIMPAR");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        jPanel6.add(btLimpar);
        btLimpar.setBounds(700, 10, 75, 22);

        btMenu.setBackground(new java.awt.Color(153, 153, 153));
        btMenu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btMenu.setText("Menu");
        btMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuActionPerformed(evt);
            }
        });
        jPanel6.add(btMenu);
        btMenu.setBounds(830, 320, 80, 28);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(10, 210, 960, 50);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTA DE PACIENTES", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel7.setLayout(null);

        jTable2Geral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "SEXO", "DATA DE NACIMENTO", "TELEFONE", "ENDEREÇO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2Geral.setColumnSelectionAllowed(true);
        jTable2Geral.setDragEnabled(true);
        jTable2Geral.setSelectionBackground(new java.awt.Color(0, 102, 51));
        jScrollPane2.setViewportView(jTable2Geral);
        jTable2Geral.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel7.add(jScrollPane2);
        jScrollPane2.setBounds(30, 20, 900, 60);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(10, 270, 960, 100);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(10, 110, 980, 420);

        btPesquisar.setBackground(new java.awt.Color(204, 204, 255));
        btPesquisar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btPesquisar.setText("Pesquisar");
        jPanel4.add(btPesquisar);
        btPesquisar.setBounds(640, 80, 81, 22);
        jPanel4.add(pesquisaPaciente);
        pesquisaPaciente.setBounds(750, 80, 240, 22);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 1000, 550);

        setSize(new java.awt.Dimension(1016, 559));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLimparActionPerformed

    private void enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoActionPerformed

    private void btNovoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoCadastroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btNovoCadastroActionPerformed

    private void btAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgendarActionPerformed
        // TODO add your handling code here:
        new Agendar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btAgendarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
       
                 
         Paciente p = new Paciente();
        
        p.setNome(txtNome.getText());
        p.setEndereco(endereco.getText());
        p.setTelefone(txtTelefone.getText());
        p.setHistoricoMedico(txtHistorico.getText());
        p.setSexo(sexo.getSelectedItem().toString());
        p.setDataNascimento(java.sql.Date.valueOf(txtDataNascimento.getText().trim()));
        p.setAtivo(true);            
        PacienteDao dao = new PacienteDao();
        
        dao.Salvar(p);
        idPaciente.setText(String.valueOf(p.getId_paciente()));
    }//GEN-LAST:event_btSalvarActionPerformed

    private void sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoActionPerformed

    private void idPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPacienteActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // TODO add your handling code here:
        Paciente p = new Paciente();
        p.setId_paciente( Integer.parseInt(idPaciente.getText()));
        
    p.setId_paciente(Integer.parseInt(idPaciente.getText()));
    p.setNome(txtNome.getText());
    p.setSexo(sexo.getSelectedItem().toString());
    p.setDataNascimento(java.sql.Date.valueOf(txtDataNascimento.getText().trim()));
    p.setTelefone(txtTelefone.getText());
    p.setEndereco(endereco.getText());
    p.setHistoricoMedico(txtHistorico.getText());
    p.setAtivo(true);
    PacienteDao dao = new PacienteDao();
    dao.atualizar(p);
    
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
    if (idPaciente.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Selecione um paciente!");
        return;
    }

    int id = Integer.parseInt(idPaciente.getText());

    PacienteDao dao = new PacienteDao();
    dao.deletar(id);

    }//GEN-LAST:event_btExcluirActionPerformed

    private void txtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascimentoActionPerformed

    private void btMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuActionPerformed
        // TODO add your handling code here:
        new MenuPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btMenuActionPerformed

    private void btMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenu1ActionPerformed
        // TODO add your handling code here:
        new MenuPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btMenu1ActionPerformed

    private void btMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenu2ActionPerformed
        // TODO add your handling code here:
        new MenuPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PacienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PacienteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DADOSPACIENTE;
    private javax.swing.JButton btAgendar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btMenu;
    private javax.swing.JButton btMenu1;
    private javax.swing.JButton btMenu2;
    private javax.swing.JButton btNovoCadastro;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextField endereco;
    private javax.swing.JTextField idPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2Geral;
    private javax.swing.JTextField pesquisaPaciente;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtHistorico;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

   
}
